### PR TITLE
replace BlazorStateComponent to IBlazorStateComponent in Subscriptions

### PR DESCRIPTION
**Pull request by megafetis**
It will help to create subscribable `LayoutComponentBase` components and `InputBase` components using method from documentation:
```cs
protected T GetState<T>()
    {
      Type stateType = typeof(T);
      Subscriptions.Add(stateType, this); // where this is IBlazorStateComponent
      return Store.GetState<T>();
    }

```

### CODE REVIEW

**Comment by StevenTCramer** [comment]
@megafetis Thanks for the PR.  It looks good. Thanks much.

**Comment by neozhu** [comment]
hello @megafetis 
How to inherit BlazorStateComponent  on the main page that has inherited LayoutComponentBase?
as we know, the blazor component does not support multi inherit classes.

**Comment by StevenTCramer** [comment]
@neozhu as you state you can't inherit from multiple classes in C#.  But you can implement multiple interfaces.  So you could implement IBlazorStateComponent in your Layout Component.  See #305.

**Comment by neozhu** [comment]
@StevenTCramer Thanks for the tip, I got it

**Comment by StevenTCramer** [comment]
@neozhu I move the Layout functionality into a `Page` component. 

https://github.dev/TimeWarpEngineering/timewarp-architecture/tree/master/Source/TimeWarp.Architecture.Template/templates/TimeWarp.Architecture/Source/ContainerApps/Web/Web.Spa/Components

My actual layout is nearly empty.

https://github.dev/TimeWarpEngineering/timewarp-architecture/tree/master/Source/TimeWarp.Architecture.Template/templates/TimeWarp.Architecture/Source/ContainerApps/Web/Web.Spa/Components

**Pull request merged**
